---
# tasks file for qs_ad
- name: Gather OS Specific Vars
  include_vars: '{{ item }}'
  with_first_found: 
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_distribution }}.yml'
    - 'main.yml'
  tags: vars
- import_tasks: QS_AD_RHEL7.yml
  tags: rhel7_ad
  when:
    (ansible_facts['os_family'] == "RedHat") and
    (ansible_facts['distribution_major_version'] == "7")
- import_tasks: QS_AD_RHEL8.yml
  tags: rhel8_ad
  when:
    (ansible_facts['os_family'] == "RedHat") and
    (ansible_facts['distribution_major_version'] == "8")
- import_tasks: QS_AD_Ubuntu.yml
  tags: ubuntu_ad
  when: 
    (ansible_facts['distribution'] == "Ubuntu") and
    (ansible_facts['distribution_version'] >= "18.04")
...