---
- hosts: all
  become: true
  ignore_errors: true
  roles:
    - qs_audit/qs_auditd
    - qs_baseline_remediation/qs_baseline_remediation
    - qs_clamav/qs_clamav_install
    - qs_fw/qs_firewall
    - qs_gdm/qs_gdm_banner
    - qs_network_time/qs_network_time
    - qs_ssh/qs_ssh
    - qs_ad/qs_ad
...