---
- name: Gather OS Specific Vars
  include_vars: '{{ item }}'
  with_first_found: 
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_distribution }}.yml'
    - 'main.yml'
  tags: vars
- import_tasks: GES_Ubuntu.yml
  tags: ubuntu_clamav
  when: 
    (ansible_facts['distribution'] == "Ubuntu") or 
    (ansible_facts['distribution'] == "Pop!_OS") and
    (ansible_facts['distribution_version'] >= "18.04")
- import_tasks: GES_RHEL.yml
  tags: rhel_clamav
  when:
    (ansible_facts['os_family'] == "RedHat") and  
    (ansible_facts['distribution_major_version'] >= "7")
...