---
# tasks file for fpd_baseline_remediation
- name: Gather OS Specific Vars
  include_vars: "{{ item }}"
  with_first_found: 
#    - '{{ ansible_distribution }}.yml'
#    - 'RHEL.yml'
    - 'main.yml'
- import_tasks: FPD_RHEL.yml
  tags: rhel_remediation
  when: 
    (ansible_facts['os_family'] == "RedHat") and  
    (ansible_facts['distribution_major_version'] >= "7")
- import_tasks: FPD_Ubuntu.yml
  tags: ubuntu_remediation
  when: 
    (ansible_facts['distribution'] == "Ubuntu") and 
    (ansible_facts['distribution_version'] >= "18.04")
...