---
- name: Apply Windows Updates
  hosts: all
  tasks:
  - name: Apply All Updates to Windows Systems
    win_updates:
      category_names: 
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        - Updates
        - ServicePacks
  - name: Reboot Systems 5 minutes After updates Have Been Applied
    win_reboot:
      reboot_timeout: 300
...