---
- name: Install Google Chrome
  hosts: all 
  tasks:
  - name: Install the latest Google Chrome from Chocolately Internet Source
    win_chocolatey:
      name: googlechrome
      state: present
...