---
- name: Update all packages to the latest version in RHEL-based Linux
  hosts: all
  become: true
  ignore_errors: true
  tasks:
  - name: Run 'yum update' against the target
    yum:
      name: '*'
      state: latest
...