---
- name: Create the qs_admin User/Group on Ubuntu Systems
  hosts: all
  become: true
  ignore_errors: true
  tasks:
  - name: Create the 'qs_admin' Group
    group:
      name: qs_admin
      state: present
  - name: Create the 'qs_admin' User for Ubuntu with the appropriate group affiliations
    user: 
      name: qs_admin
      comment: qs_admin
      home: /home/qs_admin
      shell: /bin/bash
      update_password: always
      password: '$6$quantum$VKM1ZQhVDyFAuIBzStf.8pfwNz0D8GLksQX3ZsDGu0G03pWo3utTOu.ieY7SHNFMdZ8tvPG93qTUT.6QL3a3D/'
      groups: qs_admin,sudo
...