---
# tasks file for qs_firewall
- import_tasks: configure_firewalld.yml
  tags: rhel_fw
  when:  
    (ansible_facts['os_family'] == "RedHat") and  
    (ansible_facts['distribution_major_version'] >= "7")
- import_tasks: configure_ufw.yml
  tags: ubuntu_fw
  when:
    (ansible_facts['distribution'] == "Ubuntu") and 
    (ansible_facts['distribution_version'] >= "18.04")
...